services:
  pycsw:
    build:
      context: pycsw
    volumes:
      - ./data/pycsw:/home/pycsw/data/
    ports:
      - 5000:8000
    environment:
      - PYCSW_CONFIG=/home/pycsw/data/config.yml
      - ALLOWED_IPS=${ALLOWED_IPS}
    develop:
      watch:
        - action: rebuild
          path: pycsw
        - action: restart
          path: data/pycsw/config.yml

  pycsw-harvester:
    build:
      context: pycsw
    volumes:
      - ./data/pycsw:/home/pycsw/data/
    entrypoint: /usr/local/bin/start-cron.sh
    environment:
      - PYCSW_CONFIG=/home/pycsw/data/config.yml
      - ALLOWED_IPS=${ALLOWED_IPS}
    develop:
      watch:
        - action: rebuild
          path: pycsw
        - action: restart
          path: data/pycsw/config.yml

  pygeoapi:
    build:
      context: pygeoapi
    ports:
      - 5001:80
    volumes:
      - ./data/pygeoapi/:/pygeoapi/config
    environment:
      - PYGEOAPI_SERVER_URL='http://localhost:5001'
    develop:
      watch:
        - path: pygeoapi/Dockerfile
          action: rebuild
        - path: pygeoapi/pyproject.toml
          action: rebuild
        - path: pygeoapi/entrypoint.sh
          action: rebuild
