[project]
name = "pycsw"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django-environ>=0.12.0",
    "duckdb>=1.4.3",
    "s3fs>=2026.1.0",
    "schedule>=1.2.2",
    "structlog>=25.5.0",
    "typer>=0.21.1",
]
